name: email_auth
description: A Flutter package to verify emails using OTP based method, to make sure we get real world data.
version: 1.0.0
homepage: https://github.com/saran-surya/email_auth.git
issue_tracker: https://github.com/saran-surya/email_auth/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
